/**
 * Seed for the Services library — all twenty-two, transcribed from
 * `docs/contract-content.md` §4 through §4ac.
 *
 * `sortOrder` follows the canonical ordering in contract-system.md §3, which is
 * what fixes Part numbering: 01–10 Build, 11–16 Retainer, 17–20 Setup, 21–22
 * Audit. A Service belongs to exactly one Schedule, and where the same work is
 * built once and then operated monthly that is two Services — 08/09/10 build,
 * 16 operates.
 *
 * These seed the database and are then owned by it. Editing a Service in admin
 * afterwards must never change a contract already generated; a contract holds
 * its own copy of every Part it includes.
 *
 * `[bracketed]` values are blanks and are left exactly as drafted.
 *
 * **Not carried here, deliberately.** The boundary rules in content §4e, §4i,
 * §4n, §4s, §4v, §4aa and §4ad are selection guidance for whoever builds the
 * contract ("does it sell through a cart? → Part 01"), not text a Client ever
 * reads — content §4e says so in as many words. And the platform matrix in §4o
 * belongs to the *contract*, not the service: two Clients buying Part 12 have
 * different matrices. Both are their own features; neither is service data.
 */

import type { ContractService } from '../service';

export const SERVICES: ContractService[] = [
  {
    code: '01',
    name: 'Shopify storefront',
    scheduleKey: 'build',
    sortOrder: 1,
    archived: false,
    dependencies: [],
    pairings: ['17', '19', '05'],
    overview: [
      "Setup, customisation and deployment of a Shopify storefront, built on a selected Shopify theme and adapted to the Client's brand. The result is a live, responsive store ready to take orders.",
    ],
    included: [
      'Store setup and configuration',
      'Selection and customisation of one Shopify theme',
      'Homepage build',
      'Collection page and product page templates',
      'Navigation and menu structure',
      "Cart and checkout configuration within Shopify's native settings",
      "Shipping zones, tax settings and payment method setup using the Client's accounts",
      'Policy pages populated with Client-supplied copy',
      'Mobile and tablet responsiveness',
      'Shopify-native SEO fields — titles, descriptions, alt text, URL structure',
      'Upload and organisation of up to [50] products',
      'Testing across current versions of major browsers',
      "Deployment to the Client's domain",
      'One handover walkthrough',
    ],
    accountTerms: [
      "The store is built either on the Client's own Shopify account, or on a development store that is transferred to the Client's account before launch. Either way, the Client owns the store from launch and holds the account.",
      'Qera Private Limited holds staff access during the build and for the support window. Access is removed on request or at the end of the support window, whichever occurs first.',
      "The Shopify subscription is paid by the Client directly. Where a paid theme is used, the licence is purchased in the Client's name and belongs to the Client.",
    ],
    limits: [
      { label: 'Page templates customised', value: '[8]' },
      { label: 'Products uploaded', value: '[50]' },
      { label: 'Collections', value: '[10]' },
      { label: 'Themes', value: '[1], selected before start' },
      { label: 'Revision rounds', value: '[3]' },
      { label: 'Languages', value: '[1]' },
      { label: 'Currencies', value: '[1]' },
    ],
    limitsNotes: [
      'Anything beyond these is Additional Work.',
      'Page templates are the counted unit for design and build. Products and collections are counted separately because they use an existing template and represent upload rather than design. Fifty products is one product template, not fifty pages.',
      'A page that cannot be produced from an approved template counts as a new template.',
      'Product upload beyond the stated count is quoted per additional block of [25] products.',
    ],
    completion: [
      "The store is live on the Client's domain, orders can be placed end to end through a test transaction, all pages listed above exist and display correctly on current desktop and mobile browsers, and the stated number of products are uploaded and organised.",
      'Small rendering differences between browsers, devices and operating systems are normal and do not indicate incomplete work.',
    ],
    receives: [
      'Full ownership of the Shopify store and account',
      'All customisations, which live inside the store and transfer with it',
      "The theme licence, in the Client's name",
      'Any Figma design file produced for this project, as a .fig file',
      'All final image and graphic assets produced by Qera Private Limited for this store',
      'A handover walkthrough covering how to add products, edit pages and manage orders',
    ],
    receivesNotes: [
      'There is no separate code repository for this engagement. Theme customisations exist within the Shopify store and are handed over with it.',
    ],
    thirdPartyCosts:
      'Shopify subscription · domain registration and renewal · paid theme, if used · any paid apps · payment gateway and transaction fees · fonts requiring a commercial licence · stock imagery, if used',
    exclusionIds: [
      'E01', 'E02', 'E03', 'E04', 'E05', 'E06', 'E12', 'E13', 'E14', 'E15', 'E16',
      'E17', 'E18', 'E19', 'E20', 'E21', 'E22', 'E33', 'E34', 'E35', 'E41', 'E42',
    ],
    clientInputIds: ['I01', 'I02', 'I03', 'I04', 'I05', 'I06', 'I07', 'I08', 'I09', 'I10'],
    fee: [
      { label: 'Fee', value: '[ ]' },
      { label: 'Payment', value: '[50%] on signing, [50%] before launch' },
      { label: 'Timeline', value: '[3] weeks from start date' },
      { label: 'Support', value: '[30] days from acceptance' },
    ],
  },
  {
    code: '02',
    name: 'Custom web build',
    scheduleKey: 'build',
    sortOrder: 2,
    archived: false,
    dependencies: [],
    pairings: ['17', '18', '19', '05'],
    overview: [
      'Design and development of a custom website built in code rather than on a visual builder or storefront platform. The Client receives a live site, the repository containing it, and the ability to have it maintained by any competent developer.',
      'Use this Part where the work involves writing code. Where the site is assembled on a visual builder, use Part 03. Where the site is a storefront, use Part 01.',
    ],
    included: [
      'Technical architecture and stack selection',
      'Page design for up to [10] page templates',
      'Front-end development of all designed templates',
      'Responsive implementation across mobile, tablet and desktop',
      'Content management setup for up to [3] editable content types, where a CMS is in scope',
      'Navigation, routing and URL structure',
      'Contact or enquiry form with delivery to [1] named destination',
      'Standard technical SEO — metadata, sitemap, robots file, semantic markup, canonical URLs',
      'Basic performance optimisation — image handling, code splitting, caching headers',
      "Deployment to the Client's hosting account",
      'Repository handover',
      'One handover walkthrough',
    ],
    accountTerms: [
      'Hosting takes one of two forms, selected before start.',
      "Where the Client hosts, the site is deployed to a hosting account in the Client's name. Where the account is created by Qera Private Limited, it is created in the Client's name and belongs to the Client from creation.",
      "Where Qera Private Limited hosts — available only alongside Part 14 — the site runs on infrastructure managed by Qera Private Limited, and hosting cost is included in the Part 14 fee. The Client is not locked in by this arrangement: on request or on ending, Qera Private Limited shall migrate the deployment to an account of the Client's choosing, or provide a complete export and configuration record sufficient for any competent developer to redeploy it, within [14 days] and at no charge.",
      'The repository is created in a Qera Private Limited organisation during development and transferred to the Client on receipt of full payment.',
      'Qera Private Limited retains ownership of its internal starter framework, component library and reusable systems. Where these form part of the delivered site, the Client receives a perpetual, non-exclusive, royalty-free licence to use, modify and host them as part of this site. The Client does not receive the right to redistribute, resell or reuse them in a separate project. This licence is granted on full payment and cannot be revoked.',
      'Administrative access to hosting and DNS is held by Qera Private Limited through the build and support window, and released under the Setup Schedule.',
    ],
    limits: [
      { label: 'Page templates', value: '[10]' },
      { label: 'Editable content types, where a CMS is in scope', value: '[3]' },
      { label: 'Records across all content types', value: '[50]' },
      { label: 'Forms', value: '[1]' },
      { label: 'Third-party integrations', value: '[2], named before start' },
      { label: 'Revision rounds', value: '[3]' },
      { label: 'Languages', value: '[1]' },
    ],
    limitsNotes: [
      'Anything beyond these is Additional Work.',
      'Page templates are the counted unit. A template is a layout designed and built once. The number of pages or records using an existing template is not limited and is not Additional Work.',
      'A page that cannot be produced from an approved template counts as a new template.',
      'The default ten templates are: home, about, contact, service listing, single service, technical or specification, process, terms, privacy, and 404. Where a Client needs a different set, agree the list before start and record it here.',
      'Content types are kinds of repeatable content — blog posts, case studies, team members, projects — where the Client adds and edits entries itself. Three content types means three such kinds, with an unlimited number of entries in each. Pages that exist only once, such as the home or contact page, are built directly and are editable where the Part states so.',
    ],
    completion: [
      "The site is live on the Client's domain, every page template listed above exists and functions as described, forms deliver to the named destination, the site displays correctly on current desktop and mobile browsers, and the repository has been transferred.",
      'Small rendering differences between browsers, devices and operating systems are normal and do not indicate incomplete work.',
      'Performance, ranking and traffic outcomes are not acceptance criteria.',
    ],
    receives: [
      'The repository, transferred to an account the Client controls',
      'A licence to the internal framework components used in the site, as set out above',
      'Full ownership of the hosting account and deployment',
      'Environment variables and configuration required to run and deploy the site',
      'Any Figma design file produced for this project, as a .fig file',
      'All final image and graphic assets produced by Qera Private Limited for this site',
      'A handover walkthrough covering deployment, content editing and routine changes',
    ],
    receivesNotes: [],
    thirdPartyCosts:
      'Hosting · domain registration and renewal · CMS subscription, where a hosted CMS is used · commercial font licences · stock imagery, if used · any paid third-party service used by the site · email delivery service for forms, where volume requires one',
    exclusionIds: [
      'E01', 'E02', 'E03', 'E04', 'E05', 'E06', 'E09', 'E11', 'E13', 'E21', 'E22',
      'E23', 'E24', 'E25', 'E26', 'E27', 'E28', 'E36', 'E41', 'E42', 'E43', 'E47',
      'E48', 'E49', 'E50', 'E52', 'E53',
    ],
    clientInputIds: [
      'I01', 'I02', 'I03', 'I09', 'I12', 'I14', 'I15', 'I16', 'I17', 'I18', 'I19',
      'I20', 'I26', 'I27', 'I28', 'I31', 'I33', 'I35', 'I36', 'I37',
    ],
    fee: [
      { label: 'Fee', value: '[ ]' },
      { label: 'Payment', value: '[50%] on signing, [50%] before launch' },
      { label: 'Timeline', value: '[6] weeks from start date' },
      { label: 'Support', value: '[30] days from acceptance' },
    ],
  },
  {
    code: '03',
    name: 'Webflow or Framer site',
    scheduleKey: 'build',
    sortOrder: 3,
    archived: false,
    dependencies: [],
    pairings: ['17', '19', '05'],
    overview: [
      "Design and build of a website on a visual development platform — Webflow or Framer — adapted to the Client's brand. The Client receives a live site and full ownership of the project inside their own platform account, editable without a developer.",
      'Use this Part where the site is assembled on a visual builder. Where the work involves writing an application in code, use Part 02.',
    ],
    included: [
      'Platform and plan selection',
      'Design and build of up to [10] page templates',
      "Responsive implementation across the platform's breakpoints",
      'Collection or CMS setup for up to [3] content types, where the plan supports it',
      'Navigation, routing and URL structure',
      "Contact or enquiry form using the platform's native form handling",
      'Platform-native SEO fields — page titles, descriptions, alt text, URL slugs, sitemap',
      'Native interactions and transitions available within the platform',
      'Domain connection and publishing',
      "Project transfer to the Client's account",
      'One handover walkthrough',
    ],
    accountTerms: [
      "The site is built in a Qera Private Limited workspace during development and transferred to the Client's own platform account on receipt of full payment. The Client owns the project from transfer.",
      "The platform subscription is paid by the Client directly. Where a paid template is used, it is licensed in the Client's name.",
      'Qera Private Limited holds collaborator access during the build and for the support window. Access is removed on request or at the end of the support window, whichever occurs first.',
    ],
    limits: [
      { label: 'Page templates', value: '[10]' },
      { label: 'CMS collections', value: '[3]' },
      { label: 'Records across all collections', value: '[50]' },
      { label: 'Forms', value: '[1]' },
      { label: 'Third-party embeds or integrations', value: '[2], named before start' },
      { label: 'Revision rounds', value: '[3]' },
      { label: 'Languages', value: '[1]' },
    ],
    limitsNotes: [
      'Anything beyond these is Additional Work.',
      'Page templates are the counted unit. A template is a layout designed and built once. The number of pages or collection records using an existing template is not limited and is not Additional Work.',
      'A page that cannot be produced from an approved template counts as a new template.',
      'The default ten templates are: home, about, contact, service listing, single service, technical or specification, process, terms, privacy, and 404. Where a Client needs a different set, agree the list before start and record it here.',
      'Functionality not natively supported by the selected platform and plan is outside this Part. Where the Client requires it, the work moves to Part 02 or is quoted as Additional Work.',
    ],
    completion: [
      "The site is published on the Client's domain, every page template listed above exists and functions as described, forms deliver to the named destination, the site displays correctly at the platform's standard breakpoints on current browsers, and the project has been transferred to the Client's account.",
      'Small rendering differences between browsers, devices and operating systems are normal and do not indicate incomplete work.',
    ],
    receives: [
      'Full ownership of the project within their own platform account',
      'Editor and designer access under their own subscription',
      'Any Figma design file produced for this project, as a .fig file',
      'All final image and graphic assets produced by Qera Private Limited for this site',
      'A handover walkthrough covering editing, publishing and CMS management',
    ],
    receivesNotes: [
      'There is no code repository for this engagement. The site exists within the platform and is handed over with the project.',
    ],
    thirdPartyCosts:
      'Platform subscription and site plan · domain registration and renewal · paid templates, if used · commercial font licences · stock imagery, if used · any paid third-party embed or service',
    exclusionIds: [
      'E01', 'E02', 'E03', 'E04', 'E05', 'E06', 'E09', 'E11', 'E13', 'E15', 'E16',
      'E21', 'E22', 'E25', 'E26', 'E28', 'E29', 'E30', 'E31', 'E35', 'E36', 'E41',
      'E42', 'E43', 'E47', 'E48', 'E49', 'E50', 'E51', 'E53',
    ],
    clientInputIds: [
      'I01', 'I02', 'I09', 'I12', 'I14', 'I15', 'I16', 'I17', 'I18', 'I19', 'I20',
      'I26', 'I27', 'I28', 'I31', 'I33', 'I35', 'I36', 'I37',
    ],
    fee: [
      { label: 'Fee', value: '[ ]' },
      { label: 'Payment', value: '[50%] on signing, [50%] before launch' },
      { label: 'Timeline', value: '[4] weeks from start date' },
      { label: 'Support', value: '[30] days from acceptance' },
    ],
  },
  {
    code: '04',
    name: 'Landing page or funnel',
    scheduleKey: 'build',
    sortOrder: 4,
    archived: false,
    dependencies: [],
    pairings: ['19', '07', '13'],
    overview: [
      'Design and build of a small set of pages aimed at a single conversion goal — a campaign page, a lead capture page, or a short sequence leading to one action. Built for speed of delivery and measurable response rather than as a full site.',
      'Use this Part where the scope is a single conversion goal and a small page count. Where the Client needs a full site with navigation, multiple sections and ongoing content, use Part 02 or Part 03.',
    ],
    included: [
      'One conversion goal, defined and agreed before start',
      'Design and build of up to [3] pages, including any thank-you or confirmation page',
      'Responsive implementation across mobile, tablet and desktop',
      'One lead capture or enquiry form with delivery to [1] named destination',
      "Connection to [1] named email or CRM destination, where the Client's account is provided",
      'Conversion event setup on the Client’s existing analytics, where access is provided',
      'Page-level SEO fields',
      "Deployment to the Client's domain or subdomain",
      'One handover walkthrough',
    ],
    accountTerms: [
      "Pages are deployed to a hosting or platform account in the Client's name. Where the account is created by Qera Private Limited, it is created in the Client's name and belongs to the Client from creation.",
      'Where pages are built in code, the repository is transferred on full payment and the framework licence described in Part 02 applies on the same terms. Where pages are built on a visual platform, the project is transferred on full payment.',
    ],
    limits: [
      { label: 'Pages', value: '[3]' },
      { label: 'Conversion goals', value: '[1]' },
      { label: 'Forms', value: '[1]' },
      { label: 'Form fields', value: '[6]' },
      { label: 'Destination integrations', value: '[1], named before start' },
      { label: 'Revision rounds', value: '[2]' },
      { label: 'Design variants for testing', value: '[0]' },
    ],
    limitsNotes: [
      'Anything beyond these is Additional Work.',
      'This Part does not include navigation systems, content management, blog structures or multi-section site architecture. Where those are required, the work moves to Part 02 or Part 03.',
    ],
    completion: [
      'The pages are live at the agreed address, the form submits successfully to the named destination through a test submission, the conversion event fires where analytics access was provided, and the pages display correctly on current desktop and mobile browsers.',
      'Conversion rate, lead volume, cost per lead and campaign performance are not acceptance criteria and are not guaranteed.',
    ],
    receives: [
      'The repository or platform project, transferred as set out above',
      'Full ownership of the hosting or platform account',
      'Any Figma design file produced for this project, as a .fig file',
      'All final image and graphic assets produced by Qera Private Limited for these pages',
      'A handover walkthrough covering editing, publishing and where submissions arrive',
    ],
    receivesNotes: [],
    thirdPartyCosts:
      'Hosting or platform subscription · domain or subdomain costs · CRM or email platform subscription · commercial font licences · stock imagery, if used · advertising spend',
    exclusionIds: [
      'E01', 'E02', 'E03', 'E04', 'E06', 'E09', 'E11', 'E13', 'E15', 'E19', 'E22',
      'E25', 'E26', 'E30', 'E31', 'E36', 'E38', 'E39', 'E40', 'E41', 'E43', 'E46',
      'E47', 'E48', 'E49', 'E50', 'E52', 'E53',
    ],
    clientInputIds: [
      'I01', 'I02', 'I07', 'I09', 'I12', 'I14', 'I16', 'I17', 'I18', 'I19', 'I26',
      'I27', 'I28', 'I31', 'I33', 'I35', 'I37', 'I38',
    ],
    fee: [
      { label: 'Fee', value: '[ ]' },
      { label: 'Payment', value: '[50%] on signing, [50%] before launch' },
      { label: 'Timeline', value: '[2] weeks from start date' },
      { label: 'Support', value: '[30] days from acceptance' },
    ],
  },
  {
    code: '05',
    name: 'Brand identity',
    scheduleKey: 'build',
    sortOrder: 5,
    archived: false,
    dependencies: [],
    pairings: ['06', '01', '02', '03', '11'],
    overview: [
      "Creation of a visual identity for the Client's business — logo, typography, colour and the rules governing their use. The Client receives a complete identity they own outright, in every file format needed to apply it across print, screen and third-party suppliers.",
      'This Part covers visual identity only. Naming, tagline and verbal identity are not included.',
    ],
    included: [
      'Discovery session and written direction, agreed before design begins',
      '[2] initial identity directions, presented together',
      'Development of [1] selected direction to completion',
      'Primary logo plus [3] variants — typically horizontal, stacked and icon-only',
      'Monochrome and reversed versions of every variant',
      'Typography selection — [2] typefaces, with weights and usage rules',
      'Colour palette with primary, secondary and neutral values, in HEX, RGB and CMYK',
      'Clear space, minimum size and misuse rules',
      '[2] supporting brand elements — pattern, texture, graphic device or similar',
      'Brand guidelines document covering all of the above',
      'Full file export in vector and raster formats',
      'One handover walkthrough',
    ],
    accountTerms: [
      'Ownership of the final approved identity transfers to the Client on receipt of full payment. This includes the logo, its variants, the palette, the layouts and the guidelines document.',
      'Unselected directions, exploratory work and rejected concepts remain the property of Qera Private Limited and may be developed for other purposes.',
      "Originality and trademark. Every identity is designed as original work. Before presenting any direction, Qera Private Limited carries out reasonable checks — public trademark register searches in the Client's primary market, general and image-based web searches, and domain and social handle availability — and shall not knowingly present a mark that conflicts with something already in use. Where a check raises a concern, the Client is told before the direction goes further.",
      "These checks are professional diligence, not legal clearance. Qera Private Limited is not a trademark attorney and cannot search every register, class or territory, and cannot guarantee that a mark is registrable or free from third-party rights. Before commercial use or filing, the Client should obtain formal clearance from a trademark attorney, and Qera Private Limited shall supply whatever the Client's attorney needs to carry that out. Responsibility for the decision to adopt and register a mark, and for any claim arising from it, rests with the Client.",
      "Typefaces are licensed, not owned. Where a commercial typeface is selected, the licence is purchased in the Client's name and the Client is responsible for its terms and renewal. Qera Private Limited shall identify a freely licensable alternative on request.",
    ],
    limits: [
      { label: 'Initial directions presented', value: '[2]' },
      { label: 'Directions developed to completion', value: '[1]' },
      { label: 'Logo variants', value: '[3]' },
      { label: 'Typefaces', value: '[2]' },
      { label: 'Supporting brand elements', value: '[2]' },
      { label: 'Revision rounds on the selected direction', value: '[3]' },
      { label: 'Applications or mockups', value: '[3]' },
    ],
    limitsNotes: [
      'Anything beyond these is Additional Work. A request to develop a second direction to completion, or to restart from new directions after a selection has been made, is a new engagement.',
    ],
    completion: [
      'The selected direction has been approved in writing, all variants and formats listed above have been produced, and the guidelines document has been delivered.',
      'Subjective preference expressed after written approval of a direction is not grounds for rejection and is addressed under the Additional Work terms of this Schedule.',
    ],
    receives: [
      'Logo files in vector format — AI or SVG, plus EPS and PDF',
      'Logo files in raster format — PNG with transparency, at standard sizes',
      'Favicon and app icon exports',
      'Full colour specification in HEX, RGB and CMYK',
      'The brand guidelines document as a PDF',
      'The editable Figma file containing the identity, as a .fig file',
      'A handover walkthrough covering correct application',
    ],
    receivesNotes: [],
    thirdPartyCosts:
      'Commercial typeface licences · stock imagery used in mockups, if any · trademark search or filing costs · print or production costs',
    exclusionIds: [
      'E02', 'E03', 'E06', 'E07', 'E10', 'E14', 'E38', 'E39', 'E44', 'E45', 'E48',
      'E49', 'E54', 'E59', 'E60', 'E61', 'E63',
    ],
    clientInputIds: [
      'I17', 'I20', 'I21', 'I26', 'I27', 'I28', 'I29', 'I33', 'I34', 'I35', 'I36',
      'I37', 'I42', 'I43',
    ],
    fee: [
      { label: 'Fee', value: '[ ]' },
      { label: 'Payment', value: '[50%] on signing, [50%] before final file release' },
      { label: 'Timeline', value: '[4] weeks from start date' },
      { label: 'Support', value: '[30] days from acceptance' },
    ],
  },
  {
    code: '06',
    name: 'Design system',
    scheduleKey: 'build',
    sortOrder: 6,
    archived: false,
    dependencies: ['05'],
    pairings: ['02', '03'],
    overview: [
      'Creation of a reusable component library and design foundation in Figma, so that future screens and pages can be assembled consistently without redesigning from scratch each time.',
      'This Part produces design files. It does not produce code. Where components are to be built in code, that work sits under Part 02.',
    ],
    included: [
      'Audit of existing design files or interfaces, where they exist',
      'Design tokens — colour, typography, spacing, radius, elevation, breakpoints',
      'Component library of up to [30] components, with variants and states',
      'Interactive and disabled states for every component where applicable',
      'Responsive behaviour defined at [3] breakpoints',
      'Layout grid and spacing system',
      'Usage documentation within the Figma file',
      '[3] example screens assembled from the library, to demonstrate correct use',
      'Figma library published for Client use',
      'One handover walkthrough',
    ],
    accountTerms: [
      'The system is built in a Qera Private Limited Figma workspace and delivered as a file the Client owns. Ownership transfers on receipt of full payment.',
      'Qera Private Limited retains ownership of its internal component library, naming conventions and system methodology. Where these form the basis of the delivered system, the Client receives a perpetual, non-exclusive, royalty-free licence to use, modify and extend the delivered system within their own business. The Client does not receive the right to redistribute or resell it as a product. This licence is granted on full payment and cannot be revoked.',
      "Where a Figma organisation licence is required for library publishing, it is held on the Client's subscription.",
    ],
    limits: [
      { label: 'Components', value: '[30]' },
      { label: 'Breakpoints', value: '[3]' },
      { label: 'Example screens', value: '[3]' },
      { label: 'Themes, including dark mode', value: '[1]' },
      { label: 'Platforms — web, iOS, Android', value: '[1]' },
      { label: 'Revision rounds', value: '[3]' },
    ],
    limitsNotes: [
      'Anything beyond these is Additional Work.',
      'A component is a reusable element with defined variants and states. Instances of an existing component are unlimited. An element that cannot be produced from an existing component counts as a new component.',
    ],
    completion: [
      'Every component listed in the agreed inventory exists in the library with its defined variants and states, tokens are applied throughout rather than hardcoded, the example screens are assembled entirely from library components, and the library is published and accessible to the Client.',
    ],
    receives: [
      'The complete Figma file, as a .fig file and as a published library',
      'A licence to the underlying system as set out above',
      'Token values in a portable format for developer handoff',
      'Usage documentation within the file',
      'A handover walkthrough covering extension and maintenance',
    ],
    receivesNotes: [],
    thirdPartyCosts:
      'Figma subscription and seats · commercial typeface licences · any paid Figma plugin used in the delivered file',
    exclusionIds: [
      'E02', 'E03', 'E06', 'E09', 'E11', 'E15', 'E16', 'E25', 'E28', 'E48', 'E49',
      'E50', 'E62', 'E63',
    ],
    clientInputIds: [
      'I17', 'I18', 'I19', 'I20', 'I26', 'I27', 'I28', 'I33', 'I35', 'I36', 'I37', 'I46',
    ],
    fee: [
      { label: 'Fee', value: '[ ]' },
      { label: 'Payment', value: '[50%] on signing, [50%] before file release' },
      { label: 'Timeline', value: '[4] weeks from start date' },
      { label: 'Support', value: '[30] days from acceptance' },
    ],
  },
  {
    code: '07',
    name: 'Conversion optimisation build',
    scheduleKey: 'build',
    sortOrder: 7,
    archived: false,
    dependencies: ['19'],
    pairings: ['04', '15'],
    overview: [
      'Analysis of an existing site and implementation of a defined set of changes intended to improve conversion. Delivered once, against a fixed list of changes agreed before work begins.',
      'This Part is a one-time implementation. Ongoing testing, iteration and monitoring over successive months sit under Part 15.',
    ],
    included: [
      'Review of existing analytics covering at least [3] months of data',
      'Review of the conversion path from entry to completion',
      'Heuristic review of up to [5] key page templates',
      'A written findings document with prioritised recommendations',
      'Implementation of up to [10] agreed changes',
      'Conversion event and funnel setup, where analytics access is provided',
      'Before and after measurement setup, so results can be observed by the Client',
      'One walkthrough of findings and changes made',
    ],
    accountTerms: [
      "Work is performed on the Client's existing site, platform and analytics accounts, which remain under the Client's ownership throughout.",
      'Qera Private Limited requires administrative access for the duration of the engagement. Access is removed at the end of the support window or on request.',
      'The Client is responsible for maintaining a working backup before changes are made. Where the platform does not provide version history, Qera Private Limited shall take a copy of the affected templates before modification.',
    ],
    limits: [
      { label: 'Page templates reviewed', value: '[5]' },
      { label: 'Changes implemented', value: '[10]' },
      { label: 'Conversion goals analysed', value: '[1]' },
      { label: 'Analytics platforms', value: '[1]' },
      { label: 'Revision rounds per change', value: '[1]' },
    ],
    limitsNotes: [
      'Anything beyond these is Additional Work.',
      'A change is a discrete modification to copy, layout, form, flow or component. Rebuilding a page, restructuring navigation or replacing a template is not a change and sits under Part 02, 03 or 04.',
    ],
    completion: [
      'The findings document has been delivered, the agreed list of changes has been implemented and is live, conversion tracking fires correctly where access was provided, and the walkthrough has been delivered.',
      "Conversion rate, revenue, lead volume and any improvement over the prior period are not acceptance criteria. Conversion outcomes depend on traffic quality, offer, pricing, market conditions and seasonality, none of which are within Qera Private Limited's control. This Part delivers analysis and implementation, not a result.",
      'Where a change reduces measured performance, reverting it is included within the support window.',
    ],
    receives: [
      'The findings document as a PDF',
      'A written record of every change made, with the reasoning for each',
      "Conversion tracking and funnel configuration in the Client's analytics account",
      'Any Figma file produced for redesigned sections, as a .fig file',
      'A walkthrough of findings and changes',
    ],
    receivesNotes: [],
    thirdPartyCosts:
      'Analytics, heatmap or session recording subscriptions · testing tool subscriptions · platform subscriptions · any paid app required to implement an agreed change',
    exclusionIds: [
      'E01', 'E02', 'E03', 'E22', 'E25', 'E26', 'E38', 'E39', 'E43', 'E45', 'E46',
      'E47', 'E50', 'E52', 'E56', 'E64', 'E65', 'E66',
    ],
    clientInputIds: [
      'I01', 'I03', 'I07', 'I09', 'I26', 'I28', 'I31', 'I33', 'I37', 'I38', 'I44', 'I45',
    ],
    fee: [
      { label: 'Fee', value: '[ ]' },
      { label: 'Payment', value: '[50%] on signing, [50%] before changes go live' },
      { label: 'Timeline', value: '[3] weeks from start date' },
      { label: 'Support', value: '[30] days from acceptance' },
    ],
  },
  {
    code: '08',
    name: 'Automation build',
    scheduleKey: 'build',
    sortOrder: 8,
    archived: false,
    dependencies: [],
    pairings: ['16', '19', '02'],
    overview: [
      "Design and build of automated workflows that move data and trigger actions between the Client's existing systems — forms, spreadsheets, CRMs, messaging platforms, storefronts and internal tools. Delivered as working automations the Client owns and can operate.",
      'This Part covers rule-based automation. Where a workflow depends on a language model to interpret, generate or decide, use Part 09.',
    ],
    included: [
      'Mapping of the current process before automation',
      'Design of up to [3] workflows, documented before build',
      'Build and configuration of those workflows on the agreed platform',
      'Connection to up to [5] named systems',
      'Error handling and failure notification to [1] named destination',
      'Testing against sample data supplied by the Client',
      'Written documentation of what each workflow does and how to pause it',
      'One handover walkthrough',
    ],
    accountTerms: [
      "Workflows are built in accounts held in the Client's name. Where an account is created by Qera Private Limited, it is created in the Client's name and belongs to the Client from creation.",
      "Platform subscriptions and usage costs are paid by the Client directly, on the Client's own billing method.",
      'Qera Private Limited holds access for the build and support window, released under the Setup Schedule.',
      'Qera Private Limited retains ownership of its internal automation patterns, templates and reusable logic. The Client receives a perpetual, non-exclusive, royalty-free licence to use and modify the delivered workflows within their own business, granted on full payment and irrevocable. The Client does not receive the right to redistribute or resell them.',
    ],
    limits: [
      { label: 'Workflows', value: '[3]' },
      { label: 'Connected systems', value: '[5]' },
      { label: 'Trigger types per workflow', value: '[2]' },
      { label: 'Notification destinations', value: '[1]' },
      { label: 'Revision rounds', value: '[2]' },
    ],
    limitsNotes: [
      'Anything beyond these is Additional Work.',
      'Automation is built against the systems, data formats and platform behaviour existing at the date of build. Where a connected system changes its interface, pricing, permissions or availability, repair is Additional Work.',
    ],
    completion: [
      'Each workflow triggers correctly, completes its defined actions against test data, and reports failures to the named destination. Documentation has been delivered.',
      'Volume of leads, time saved, error rate and business outcome are not acceptance criteria.',
    ],
    receives: [
      'The workflows, in accounts the Client owns',
      'A licence to the underlying patterns as set out above',
      'Written documentation for each workflow, including how to pause or disable it',
      'A handover walkthrough covering monitoring, editing and failure response',
    ],
    receivesNotes: [],
    thirdPartyCosts:
      'Automation platform subscription · connected system subscriptions · task, operation or execution costs · messaging or email delivery costs',
    exclusionIds: [
      'E22', 'E23', 'E24', 'E27', 'E30', 'E37', 'E47', 'E48', 'E50', 'E51', 'E52',
      'E53', 'E56', 'E57', 'E67', 'E70', 'E72', 'E73',
    ],
    clientInputIds: ['I01', 'I08', 'I26', 'I27', 'I28', 'I30', 'I37', 'I47', 'I48', 'I49'],
    fee: [
      { label: 'Fee', value: '[ ]' },
      { label: 'Payment', value: '[50%] on signing, [50%] before workflows go live' },
      { label: 'Timeline', value: '[3] weeks from start date' },
      { label: 'Support', value: '[30] days from acceptance' },
    ],
  },
  {
    code: '09',
    name: 'AI assistant build',
    scheduleKey: 'build',
    sortOrder: 9,
    archived: false,
    dependencies: [],
    pairings: ['16', '08', '02'],
    overview: [
      "Design and build of an assistant powered by a third-party language model — a support responder, an internal knowledge assistant, a lead qualifier or similar — configured against the Client's own content and connected to the Client's systems.",
    ],
    included: [
      "Definition of the assistant's purpose, scope and refusal boundaries",
      'Model and provider selection',
      'System instruction design and iteration',
      'Knowledge base setup from up to [100] documents or pages supplied by the Client',
      'Retrieval configuration, where the assistant answers from Client content',
      'Connection to up to [2] named systems for lookup or action',
      'Escalation path to a human for anything outside scope',
      'Testing against [30] representative cases supplied or agreed with the Client',
      'Written documentation covering scope, limits and how to disable the assistant',
      'One handover walkthrough',
    ],
    accountTerms: [
      "The assistant runs on provider accounts held in the Client's name, on the Client's own billing method. Usage costs are paid by the Client directly.",
      'Outputs are probabilistic and are not guaranteed to be accurate, consistent or repeatable. The same input may produce different output. The assistant may state something incorrect in a confident tone.',
      'The Client is responsible for reviewing output before it is relied upon, published or acted on, and names a person accountable for that review. Qera Private Limited is not liable for any consequence of output that was published, sent or acted upon without review.',
      'The assistant must not be deployed for medical, legal, financial, employment, credit, insurance or safety decisions, or any use where an incorrect output causes regulatory exposure or physical harm, unless that use is expressly named in this Part and the Client has obtained its own compliance advice.',
      'Qera Private Limited does not use Client data to train models. Third-party providers process submitted data under their own terms, which Qera Private Limited does not control. The Client identifies any data that must not be sent to a third-party provider before build begins.',
      'Qera Private Limited retains ownership of its internal prompt patterns, evaluation methods and system architecture, licensed to the Client on the same terms as Part 08.',
    ],
    limits: [
      { label: 'Assistants', value: '[1]' },
      { label: 'Knowledge base documents at build', value: '[100]' },
      { label: 'Connected systems', value: '[2]' },
      { label: 'Deployment surfaces — site, WhatsApp, internal tool', value: '[1]' },
      { label: 'Languages', value: '[1]' },
      { label: 'Test cases', value: '[30]' },
      { label: 'Revision rounds', value: '[2]' },
    ],
    limitsNotes: ['Anything beyond these is Additional Work.'],
    completion: [
      'The assistant is deployed on the agreed surface, responds within its defined scope, escalates outside it, answers the agreed test cases acceptably as judged against the approved definition, and documentation has been delivered.',
      'Accuracy rate, resolution rate, deflection rate and customer satisfaction are not acceptance criteria and are not guaranteed. A model that answers a test case correctly at handover may answer it differently later.',
    ],
    receives: [
      'The deployed assistant, on accounts the Client owns',
      'System instructions and configuration, in a portable format',
      'Knowledge base in its source form',
      'A licence to the underlying patterns as set out above',
      'Documentation covering scope, known limits and how to disable it',
      'A handover walkthrough',
    ],
    receivesNotes: [],
    thirdPartyCosts:
      'Model and API usage costs · vector or retrieval infrastructure · hosting · platform subscriptions · messaging channel costs',
    exclusionIds: [
      'E22', 'E23', 'E27', 'E30', 'E37', 'E47', 'E48', 'E50', 'E52', 'E53', 'E54',
      'E56', 'E67', 'E68', 'E69', 'E70', 'E71', 'E72', 'E73',
    ],
    clientInputIds: [
      'I01', 'I08', 'I09', 'I26', 'I27', 'I28', 'I30', 'I37', 'I47', 'I48', 'I49', 'I50', 'I51',
    ],
    fee: [
      { label: 'Fee', value: '[ ]' },
      { label: 'Payment', value: '[50%] on signing, [50%] before deployment' },
      { label: 'Timeline', value: '[4] weeks from start date' },
      { label: 'Support', value: '[30] days from acceptance' },
    ],
  },
  {
    code: '10',
    name: 'Generative content system',
    scheduleKey: 'build',
    sortOrder: 10,
    archived: false,
    dependencies: ['05'],
    pairings: ['11', '16'],
    overview: [
      'Build of a repeatable system for producing content at volume using generative tools — templates, prompt sets, brand constraints and a defined workflow, so that the Client or Qera Private Limited can generate consistent output without starting from nothing each time.',
      'The deliverable is the system, not a content library. Content produced on an ongoing basis sits under Part 11 or Part 16.',
    ],
    included: [
      'Definition of output types and formats in scope',
      'Brand constraint set — tone, visual rules, prohibited language and subjects',
      '[5] prompt or generation templates, tested and documented',
      'Reference examples showing acceptable and unacceptable output',
      'Review checklist for output before publication',
      '[10] sample outputs produced during build, as demonstration',
      'Written documentation covering operation and limits',
      'One handover walkthrough',
    ],
    accountTerms: [
      "The system runs on provider accounts held in the Client's name, on the Client's own billing method.",
      'Generated output is not guaranteed to be original, accurate or free from resemblance to existing work. Generative tools produce output derived from training data whose composition and licensing Qera Private Limited does not control and cannot audit.',
      "Ownership and copyright status of generated output is unsettled and varies by jurisdiction. Qera Private Limited makes no assurance that generated output attracts copyright protection, that it can be registered, or that it does not infringe third-party rights. The Client is responsible for its own clearance before commercial use, and for compliance with each provider's terms including any attribution or disclosure requirement.",
      'Every output must be reviewed by a named person before publication. The Client accepts that publishing unreviewed generative output carries reputational and legal risk that sits with the Client.',
      'Qera Private Limited retains ownership of its internal prompt patterns, constraint frameworks and review methods, licensed to the Client on the same terms as Part 08.',
    ],
    limits: [
      { label: 'Output types', value: '[2]' },
      { label: 'Generation templates', value: '[5]' },
      { label: 'Sample outputs produced at build', value: '[10]' },
      { label: 'Providers or tools configured', value: '[2]' },
      { label: 'Languages', value: '[1]' },
      { label: 'Revision rounds', value: '[2]' },
    ],
    limitsNotes: ['Anything beyond these is Additional Work.'],
    completion: [
      'Every template produces output within the agreed brand constraints across the sample set, the review checklist has been delivered, and documentation is complete.',
      'Volume, engagement, reach and commercial performance of generated content are not acceptance criteria.',
    ],
    receives: [
      'All generation templates in a portable format',
      'The brand constraint set as a written document',
      'The review checklist',
      'The sample outputs produced during build',
      'A licence to the underlying patterns as set out above',
      'A handover walkthrough',
    ],
    receivesNotes: [],
    thirdPartyCosts:
      'Generative tool subscriptions · model and API usage costs · stock or reference assets · commercial typeface licences',
    exclusionIds: [
      'E01', 'E02', 'E03', 'E06', 'E07', 'E38', 'E40', 'E44', 'E46', 'E47', 'E48',
      'E54', 'E60', 'E67', 'E68', 'E69', 'E70', 'E71', 'E73',
    ],
    clientInputIds: [
      'I17', 'I19', 'I20', 'I21', 'I26', 'I27', 'I28', 'I33', 'I35', 'I36', 'I37',
      'I47', 'I50', 'I51',
    ],
    fee: [
      { label: 'Fee', value: '[ ]' },
      { label: 'Payment', value: '[50%] on signing, [50%] before handover' },
      { label: 'Timeline', value: '[3] weeks from start date' },
      { label: 'Support', value: '[30] days from acceptance' },
    ],
  },
  {
    code: '11',
    name: 'Content production',
    scheduleKey: 'retainer',
    sortOrder: 11,
    archived: false,
    dependencies: ['05'],
    pairings: ['12', '13', '10'],
    overview: [
      'Monthly planning, design and delivery of social content — static posts, carousels, stories and short-form video edits — produced against an agreed calendar and the platforms ticked on the matrix.',
      'This Part produces and publishes content. It does not include replying to the audience, which is Part 12.',
    ],
    included: [
      'A content calendar for the cycle, delivered for approval before production',
      '[12] static posts or carousels',
      '[8] stories',
      '[4] short-form video edits from Client-supplied footage',
      'Caption writing for every delivered item',
      'Hashtag and keyword selection',
      'Scheduling and publishing to the platforms ticked on the matrix',
      'A written summary at cycle end covering what was published',
    ],
    accountTerms: [
      'All platform accounts remain owned by and registered to the Client throughout. Qera Private Limited holds access only for the engagement and only for platforms on the matrix.',
      'The Client maintains its own recovery email, recovery phone and second-factor access on every account. Qera Private Limited is not liable for loss of access, restriction, suspension or enforcement action taken by a platform.',
      'Final approved content delivered in a cycle may be used by the Client for its business from the cycle in which it was paid for. Working files, unused concepts, raw footage and project files remain the property of Qera Private Limited, as set out in the Retainer Schedule.',
      'Content is produced from footage and assets supplied by the Client. Shooting, filming and photography are not included.',
    ],
    limits: [
      { label: 'Static posts or carousels', value: '[12]' },
      { label: 'Stories', value: '[8]' },
      { label: 'Short-form video edits', value: '[4]' },
      { label: 'Maximum video length', value: '[60] seconds' },
      { label: 'Slides per carousel', value: '[6]' },
      { label: 'Platforms', value: 'as ticked on the matrix' },
      { label: 'Revision rounds per item', value: '[1]' },
      { label: 'Rollover of unused capacity', value: '[2] cycles' },
    ],
    limitsNotes: [
      'Carousel slides count toward the static post allowance at [1] post per carousel of up to [6] slides.',
      'Anything beyond these is Additional Work.',
      'The same item published to more than one platform counts once, provided no separate resizing or re-editing beyond standard format adaptation is required.',
    ],
    completion: [
      'Not applicable. Delivery under this Part is measured by cycle, against the included items above.',
    ],
    receives: [
      'All final approved content for the cycle, in delivery formats',
      'The content calendar for the cycle',
      'A written summary at cycle end',
    ],
    receivesNotes: [],
    thirdPartyCosts:
      'Scheduling tool subscriptions · stock imagery, video or music licensing · commercial typeface licences · advertising spend · production or shoot costs',
    exclusionIds: [
      'E02', 'E03', 'E06', 'E07', 'E38', 'E39', 'E40', 'E44', 'E46', 'E52', 'E55',
      'E56', 'E58', 'E76', 'E77', 'E81',
    ],
    clientInputIds: [
      'I05', 'I12', 'I13', 'I14', 'I16', 'I17', 'I18', 'I19', 'I20', 'I21', 'I26',
      'I27', 'I28', 'I29', 'I36', 'I37', 'I40', 'I52',
    ],
    fee: [
      { label: 'Monthly fee', value: '[ ]' },
      { label: 'Billing', value: 'in advance, on the anniversary of first payment' },
      { label: 'Notice', value: '[15] days' },
      { label: 'Rollover of unused capacity', value: '[2] cycles' },
    ],
  },
  {
    code: '12',
    name: 'Community management',
    scheduleKey: 'retainer',
    sortOrder: 12,
    archived: false,
    dependencies: [],
    pairings: ['11', '13'],
    overview: [
      "Monitoring and responding to the Client's audience across the platforms ticked on the matrix — comments, direct messages, mentions and reviews — within an agreed tone and an agreed set of approved responses.",
      'This Part handles conversation. It does not produce content, which is Part 11.',
    ],
    included: [
      'Monitoring of comments, direct messages and mentions on platforms ticked on the matrix',
      'Responses within [1] working day, during the agreed days and hours',
      'Response handling for up to [200] interactions',
      'Use of an approved response set for common questions',
      "Escalation of anything outside the approved set to the Client's named contact",
      'Flagging and hiding of spam and abusive comments',
      'A written summary at cycle end covering volume, themes and escalations',
    ],
    accountTerms: [
      "All accounts remain owned by and registered to the Client. Qera Private Limited responds on the Client's behalf using access granted for the engagement, and only on platforms on the matrix.",
      "Qera Private Limited does not make commercial decisions on the Client's behalf. Refunds, discounts, order changes, complaint resolutions, pricing statements, delivery commitments, legal positions and public statements of fault are escalated, not answered. The Client provides a named contact and an escalation path for these.",
      'Responses are made using the approved response set and tone supplied by the Client. Where a question falls outside it, the response is escalated rather than improvised.',
      'The Client remains publisher of everything appearing on its own channels and remains responsible for the accuracy of information the Client supplied for use in responses.',
      'Coverage is limited to the agreed days and hours. This Part does not include out-of-hours, weekend or real-time coverage unless stated.',
    ],
    limits: [
      { label: 'Interactions handled per cycle', value: '[200]' },
      { label: 'Response time target', value: '[1] working day' },
      { label: 'Coverage days', value: '[Monday to Friday]' },
      { label: 'Coverage hours', value: '[09:00 to 18:00 GST]' },
      { label: 'Platforms', value: 'as ticked on the matrix' },
      { label: 'Languages', value: '[1]' },
      { label: 'Rollover of unused capacity', value: '[0] cycles' },
    ],
    limitsNotes: [
      'Anything beyond these is Additional Work.',
      'Unused interaction volume does not roll over, because capacity in this Part is standby time rather than production output.',
    ],
    completion: [
      'Not applicable. Delivery under this Part is measured by cycle, against the included items above.',
    ],
    receives: [
      'Responses issued on its channels within the agreed scope',
      'A written cycle summary covering volume, recurring themes and escalations',
      'A record of anything escalated and left unanswered',
    ],
    receivesNotes: [],
    thirdPartyCosts:
      'Inbox or social management tool subscriptions · translation services, where a second language is agreed · any paid platform feature required for messaging',
    exclusionIds: [
      'E01', 'E38', 'E40', 'E44', 'E46', 'E52', 'E56', 'E58', 'E74', 'E75', 'E76',
      'E77', 'E81',
    ],
    clientInputIds: [
      'I05', 'I21', 'I26', 'I27', 'I28', 'I29', 'I30', 'I41', 'I52', 'I53', 'I55', 'I56',
    ],
    fee: [
      { label: 'Monthly fee', value: '[ ]' },
      { label: 'Billing', value: 'in advance, on the anniversary of first payment' },
      { label: 'Notice', value: '[15] days' },
      { label: 'Rollover of unused capacity', value: '[0] cycles' },
    ],
  },
  {
    code: '13',
    name: 'Paid social management',
    scheduleKey: 'retainer',
    sortOrder: 13,
    archived: false,
    dependencies: ['19'],
    pairings: ['11', '04'],
    overview: [
      'Planning, setup and ongoing management of paid campaigns on the platforms ticked on the matrix — audience structure, campaign build, budget pacing and reporting.',
      'The management fee covers the work. Advertising spend is separate and is paid by the Client.',
    ],
    included: [
      'Campaign strategy for the cycle, against an objective agreed in writing',
      'Build and launch of up to [3] campaigns',
      'Audience and targeting setup',
      'Ad set structure and budget pacing',
      'Use of up to [6] creatives supplied under Part 11 or by the Client',
      'Ongoing optimisation — budget shifts, audience adjustment, pausing underperformers',
      'Conversion tracking review, where access is provided',
      'A written performance report at cycle end',
    ],
    accountTerms: [
      "Advertising spend is paid by the Client directly, on the Client's own payment method, registered on the Client's own ad account. Qera Private Limited does not fund, advance or hold spend on the Client's behalf under any circumstance. Where a Client's payment method fails or is declined, campaigns stop and Qera Private Limited bears no liability for the interruption.",
      'The ad account and business portfolio are owned by and registered to the Client. Qera Private Limited operates as a partner with assigned access, which is revoked on request or at the end of the engagement. Qera Private Limited does not run Client campaigns from its own ad account.',
      'The Client is responsible for the legality and accuracy of every claim, offer, price and representation in its advertising, and for compliance with advertising law and platform policy in every territory it targets.',
      "Platform enforcement — ad rejection, account restriction, spend limits, policy strikes and suspension — is outside Qera Private Limited's control. Work performed remains payable where a campaign is rejected or an account is restricted.",
    ],
    limits: [
      { label: 'Campaigns built per cycle', value: '[3]' },
      { label: 'Creatives used per cycle', value: '[6]' },
      { label: 'Platforms', value: 'as ticked on the matrix' },
      { label: 'Monthly spend managed, up to', value: '[ ]' },
      { label: 'Territories or markets', value: '[1]' },
      { label: 'Rollover of unused capacity', value: '[0] cycles' },
    ],
    limitsNotes: [
      'Anything beyond these is Additional Work. Where managed spend exceeds the stated ceiling, the management fee is renegotiated for the following cycle.',
    ],
    completion: [
      'Not applicable. Delivery under this Part is measured by cycle, against the included items above.',
      'Return on ad spend, cost per acquisition, cost per lead, reach and revenue are not deliverables and are not guaranteed, on the terms set out in the Retainer Schedule.',
    ],
    receives: [
      "Campaigns built and running in the Client's own ad account",
      'A written performance report each cycle',
      'Full retention of all campaign structures, audiences and learning within its own account on termination',
    ],
    receivesNotes: [],
    thirdPartyCosts:
      'All advertising spend · platform fees · analytics or attribution tool subscriptions · creative production beyond what Part 11 supplies · landing page or destination costs',
    exclusionIds: [
      'E01', 'E02', 'E03', 'E38', 'E40', 'E44', 'E46', 'E52', 'E54', 'E56', 'E58',
      'E65', 'E76', 'E77', 'E78', 'E79', 'E80', 'E81',
    ],
    clientInputIds: [
      'I05', 'I07', 'I14', 'I16', 'I26', 'I27', 'I28', 'I31', 'I33', 'I34', 'I37',
      'I38', 'I52', 'I54', 'I57',
    ],
    fee: [
      { label: 'Monthly management fee', value: '[ ]' },
      { label: 'Managed spend ceiling', value: '[ ]' },
      { label: 'Billing', value: 'in advance, on the anniversary of first payment' },
      { label: 'Notice', value: '[15] days' },
      { label: 'Rollover of unused capacity', value: '[0] cycles' },
    ],
  },
  {
    code: '14',
    name: 'Website maintenance',
    scheduleKey: 'retainer',
    sortOrder: 14,
    archived: false,
    dependencies: [],
    pairings: ['15', '19'],
    overview: [
      'Keeping an existing site working — applying platform and dependency updates, taking backups, monitoring availability, fixing faults and making small content changes each cycle.',
      'This Part maintains what exists. Adding pages, features or templates is a Build engagement.',
    ],
    included: [
      'Platform, framework, theme and plugin updates, applied and tested',
      'Security patch application',
      '[1] backup per week, retained for [30] days',
      'Uptime monitoring with alerting to [1] named destination',
      'Fault diagnosis and repair, within the hours below',
      'Up to [3] hours of content or minor change work',
      'Broken link and form delivery checks',
      'A written summary each cycle covering updates applied, faults fixed and work used',
    ],
    accountTerms: [
      'Hosting, platform and domain accounts remain owned by and registered to the Client. Qera Private Limited holds administrative access only for the duration of the engagement.',
      'Uptime and availability are not guaranteed. Monitoring means automated checks and alerting, not continuous human supervision and not a commitment that the site stays online. Hosting performance, platform outages, DNS failures and provider incidents sit with the providers concerned.',
      "Backups are taken as an additional safeguard and do not replace the Client's own responsibility to hold an independent copy. Where a backup fails or is incomplete, liability is limited to taking a fresh backup.",
      'Where a third-party plugin, dependency or platform update breaks existing functionality, repair within [3] hours per cycle is included. Beyond that it is Additional Work.',
      'Where the site was built by a third party, Qera Private Limited maintains it as found. Pre-existing defects, insecure code and unsupported dependencies are reported, not repaired, unless quoted separately.',
    ],
    limits: [
      { label: 'Change and repair hours per cycle', value: '[3]' },
      { label: 'Backup frequency', value: '[weekly]' },
      { label: 'Backup retention', value: '[30] days' },
      { label: 'Response time to a reported fault', value: '[1] working day' },
      { label: 'Coverage days', value: '[Monday to Friday]' },
      { label: 'Sites maintained', value: '[1]' },
      { label: 'Rollover of unused hours', value: '[1] cycle' },
    ],
    limitsNotes: [
      'Anything beyond these is Additional Work.',
      'Change work means editing existing content, swapping images, adjusting copy, updating prices and similar. It does not mean new pages, new templates, new features, redesigns or restructures.',
    ],
    completion: [
      'Not applicable. Delivery under this Part is measured by cycle, against the included items above.',
    ],
    receives: [
      'A maintained site with updates and patches applied',
      'Backups held for the stated retention period, restorable on request',
      'A written cycle summary',
      'On ending, a final backup and removal of Qera Private Limited access',
    ],
    receivesNotes: [],
    thirdPartyCosts:
      'Hosting · domain renewal · platform and CMS subscriptions · paid plugins, themes and licence renewals · monitoring or backup tool subscriptions · SSL, where not provided by the host',
    exclusionIds: [
      'E01', 'E02', 'E13', 'E15', 'E16', 'E22', 'E25', 'E26', 'E27', 'E38', 'E43',
      'E48', 'E49', 'E52', 'E56', 'E58', 'E66', 'E76', 'E82', 'E83', 'E84', 'E85',
    ],
    clientInputIds: ['I01', 'I02', 'I03', 'I26', 'I28', 'I30', 'I41', 'I58', 'I59'],
    fee: [
      { label: 'Monthly fee', value: '[ ]' },
      { label: 'Billing', value: 'in advance, on the anniversary of first payment' },
      { label: 'Notice', value: '[15] days' },
      { label: 'Rollover of unused hours', value: '[1] cycle' },
    ],
  },
  {
    code: '15',
    name: 'Conversion optimisation retainer',
    scheduleKey: 'retainer',
    sortOrder: 15,
    archived: false,
    dependencies: ['19'],
    pairings: ['14', '13', '04'],
    overview: [
      'Continuous improvement of an existing site or funnel — forming a hypothesis each cycle, making a change, measuring what happened and deciding what to do next.',
      'This Part is iterative and ongoing. A fixed list of changes delivered once is Part 07.',
    ],
    included: [
      "Review of the prior cycle's changes against measured outcome",
      '[2] prioritised hypotheses, documented before work begins',
      'Implementation of up to [4] changes',
      'Measurement setup for each change, so its effect can be observed',
      'Review of the conversion funnel for new friction points',
      'A written cycle report covering what changed, what moved and what is recommended next',
    ],
    accountTerms: [
      "Work is performed on the Client's site, platform and analytics accounts, which remain under the Client's ownership throughout.",
      'Improvement is not guaranteed. Some changes reduce measured performance. This is a normal outcome of testing, not a defect, and reverting a change is included within the cycle.',
      'Meaningful measurement requires traffic. Where a page receives fewer than [1,000] relevant visitors per cycle, results cannot be attributed with confidence and reporting is presented as directional observation rather than measured effect. The Client acknowledges this before the engagement begins.',
      "Outcomes depend on traffic quality, offer, pricing, competition, seasonality and market conditions, none of which are within Qera Private Limited's control.",
      'Where a change requires rebuilding a page, restructuring navigation or creating a new template, that work is a Build engagement.',
    ],
    limits: [
      { label: 'Hypotheses per cycle', value: '[2]' },
      { label: 'Changes implemented per cycle', value: '[4]' },
      { label: 'Pages or templates in scope', value: '[5]' },
      { label: 'Conversion goals tracked', value: '[1]' },
      { label: 'Concurrent split tests', value: '[1]' },
      { label: 'Properties', value: '[1]' },
      { label: 'Rollover of unused capacity', value: '[0] cycles' },
    ],
    limitsNotes: ['Anything beyond these is Additional Work.'],
    completion: [
      'Not applicable. Delivery under this Part is measured by cycle, against the included items above.',
      'Conversion rate, revenue, lead volume and any improvement over a prior period are not deliverables and are not guaranteed, on the terms set out in the Retainer Schedule.',
    ],
    receives: [
      'Changes implemented and live on its own property',
      'Measurement configuration in its own analytics account',
      'A written cycle report, including changes that did not work and why',
      'A cumulative record of everything tested across the engagement',
    ],
    receivesNotes: [],
    thirdPartyCosts:
      'Testing, heatmap and session recording tool subscriptions · analytics subscriptions · platform subscriptions · any paid app required to implement an agreed change · advertising spend',
    exclusionIds: [
      'E01', 'E02', 'E03', 'E22', 'E25', 'E26', 'E38', 'E39', 'E43', 'E45', 'E46',
      'E52', 'E56', 'E65', 'E66', 'E76', 'E85', 'E86',
    ],
    clientInputIds: [
      'I01', 'I03', 'I07', 'I26', 'I28', 'I31', 'I33', 'I37', 'I38', 'I44', 'I45', 'I60',
    ],
    fee: [
      { label: 'Monthly fee', value: '[ ]' },
      { label: 'Billing', value: 'in advance, on the anniversary of first payment' },
      { label: 'Notice', value: '[15] days' },
      { label: 'Rollover of unused capacity', value: '[0] cycles' },
    ],
  },
  {
    code: '16',
    name: 'AI system operation',
    scheduleKey: 'retainer',
    sortOrder: 16,
    archived: false,
    dependencies: ['08', '09', '10'],
    pairings: ['08', '09', '10'],
    overview: [
      'Ongoing operation of automations, assistants or generative systems already built — monitoring that they are running, responding when they fail, adjusting them as the Client’s business changes, and keeping them working when providers change underneath them.',
      "Without this Part, a delivered system is the Client's to operate from the end of its support window.",
    ],
    included: [
      'Monitoring of [3] systems for failure and interruption',
      'Response to failures within [2] working days of detection or report',
      'Up to [4] hours of adjustment, tuning or configuration change',
      'Review of provider changes affecting the systems in scope',
      'Review of usage costs against the prior cycle',
      'A written monthly summary covering failures, changes made and cost movement',
    ],
    accountTerms: [
      "All systems, accounts and provider billing remain in the Client's name throughout. Qera Private Limited holds operational access only, and only for systems named in this Part.",
      "Qera Private Limited does not guarantee uptime, availability, accuracy or continuity of any third-party model, platform or provider. Providers change pricing, deprecate models, alter behaviour, restrict access and discontinue services without notice and without Qera Private Limited's involvement.",
      'Where a provider change requires rebuilding rather than adjusting a system, that work is quoted separately as a Build engagement.',
      "Review of output before use remains the Client's responsibility on the same terms as the Part under which the system was built. This Part does not add a review or approval obligation.",
      "Usage costs are paid by the Client directly. Qera Private Limited monitors and reports cost movement but does not control it and is not liable for cost increases caused by usage, provider pricing or the Client's own configuration changes.",
    ],
    limits: [
      { label: 'Systems monitored', value: '[3]' },
      { label: 'Adjustment hours per cycle', value: '[4]' },
      { label: 'Failure response target', value: '[2] working days' },
      { label: 'Providers in scope', value: '[2]' },
    ],
    limitsNotes: [
      'Anything beyond these is Additional Work.',
      'This Part does not include out-of-hours response, a guaranteed resolution time, or continuous real-time monitoring. Monitoring means scheduled checks and automated failure alerts, not constant human supervision.',
      "Adjustment means change within the system's existing design. Building a new workflow, adding a new connected system, extending an assistant's scope or adding an output type is a Build engagement.",
    ],
    completion: [
      'Not applicable. Delivery under this Part is measured by cycle, against the included items above.',
    ],
    receives: [
      'Continued operation of the named systems',
      'A written monthly summary',
      "Any configuration changes made, reflected in the Client's own accounts",
    ],
    receivesNotes: [
      'On ending, all access held by Qera Private Limited is removed and configuration is left in working order as at the final cycle.',
    ],
    thirdPartyCosts:
      'Model and API usage · platform and provider subscriptions · infrastructure · messaging costs',
    exclusionIds: [
      'E22', 'E27', 'E37', 'E48', 'E49', 'E52', 'E53', 'E56', 'E57', 'E67', 'E68',
      'E69', 'E70', 'E71', 'E72', 'E73',
    ],
    clientInputIds: ['I01', 'I08', 'I26', 'I28', 'I30', 'I41', 'I47', 'I50', 'I51'],
    fee: [
      { label: 'Monthly fee', value: '[ ]' },
      { label: 'Billing', value: 'in advance, on the anniversary of first payment' },
      { label: 'Notice', value: '[15] days' },
      { label: 'Rollover of unused capacity', value: '[2] cycles' },
    ],
  },
  {
    code: '17',
    name: 'Domain and DNS',
    scheduleKey: 'setup',
    sortOrder: 17,
    archived: false,
    dependencies: [],
    pairings: ['18'],
    overview: [
      "Purchase and configuration of a domain, and setup of the DNS records needed to point it at the Client's site, email and connected services.",
    ],
    included: [
      'Availability check against up to [5] preferred names supplied by the Client',
      "Registration of [1] domain in the Client's name",
      'DNS configuration — A, CNAME, MX, TXT and any records required by connected services',
      'Email authentication records — SPF, DKIM and DMARC, where email is in scope',
      'SSL provisioning through the host or registrar',
      'Redirect configuration for [2] additional domains or subdomains, where supplied',
      'Written record of every record created',
      'Transfer of registrar access under the Setup Schedule',
    ],
    accountTerms: [
      "The domain is registered in the Client's name, with the Client as registrant, from purchase. Qera Private Limited does not hold or retain ownership of any Client domain.",
      'Administrative and DNS access is held by Qera Private Limited during any related Build engagement, because DNS changes are required throughout development, and is released under the Setup Schedule on completion and full payment.',
      "Where the domain cost is included within a Build advance, it is stated in the approved Proposal. Renewal is the Client's responsibility from the first renewal date onward.",
      "Availability of any given name cannot be guaranteed. Premium pricing, registry restrictions and prior registration are outside Qera Private Limited's control.",
    ],
    limits: [
      { label: 'Domains registered', value: '[1]' },
      { label: 'Names checked for availability', value: '[5]' },
      { label: 'Redirected domains or subdomains', value: '[2]' },
      { label: 'Connected services configured', value: '[4]' },
    ],
    limitsNotes: ['Anything beyond these is Additional Work.'],
    completion: [
      'The domain is registered to the Client, every record listed above resolves correctly, SSL is active, and the record documentation has been delivered.',
      'Propagation delays of up to forty-eight hours are normal and do not indicate incomplete work.',
    ],
    receives: [
      'The domain, registered in its own name',
      'Registrar access and credentials, on release',
      'A written record of every DNS record created',
      'Email authentication records, where email is in scope',
    ],
    receivesNotes: [],
    thirdPartyCosts:
      'Domain registration and renewal · premium domain pricing, where applicable · privacy protection · SSL, where the host charges separately',
    exclusionIds: ['E30', 'E31', 'E48', 'E49', 'E52', 'E53', 'E57', 'E83', 'E85', 'E87', 'E90'],
    clientInputIds: ['I02', 'I26', 'I27', 'I28', 'I61', 'I63'],
    fee: [
      { label: 'Fee', value: '[ ]' },
      { label: 'Payment', value: 'in full in advance, or within a Build advance' },
      { label: 'Timeline', value: '[3] working days from receipt of inputs' },
      { label: 'Correction window', value: '[14] days' },
    ],
  },
  {
    code: '18',
    name: 'Business email and workspace',
    scheduleKey: 'setup',
    sortOrder: 18,
    archived: false,
    dependencies: ['17'],
    pairings: ['17'],
    overview: [
      "Setup of a business email and productivity workspace on the Client's own domain — mailboxes, aliases, groups and the authentication records that keep mail deliverable.",
    ],
    included: [
      "Workspace creation on the Client's domain",
      'Domain verification and connection',
      'Creation of up to [5] mailboxes',
      'Creation of up to [5] aliases or groups',
      'SPF, DKIM and DMARC configuration',
      'Email signature template, applied to [1] format',
      'Basic security configuration — two-factor enforcement and recovery settings',
      'One handover walkthrough covering the admin console',
    ],
    accountTerms: [
      "The workspace is created in the Client's name and the subscription is paid by the Client on the Client's own payment method, provided before setup begins. Qera Private Limited does not hold a payment method for any Client subscription.",
      'Administrative access transfers to the Client on completion of this Part, not at the end of any wider engagement. This is the carve-out permitted under the Setup Schedule, and exists because the Client needs its email in daily use immediately.',
      "DNS records for mail remain under Qera Private Limited's administration during any related Build engagement, and are released with the domain under the Setup Schedule. Release of the workspace does not release the domain.",
      'From transfer, the Client is solely responsible for user administration, billing, security, recovery access and second-factor methods.',
      'Deliverability is not guaranteed. Inbox placement depends on sending behaviour, list quality, recipient filtering and sender reputation built over time, none of which are set at configuration.',
    ],
    limits: [
      { label: 'Mailboxes created', value: '[5]' },
      { label: 'Aliases or groups', value: '[5]' },
      { label: 'Signature formats', value: '[1]' },
      { label: 'Domains connected', value: '[1]' },
      { label: 'Mailbox migrations', value: '[0]' },
    ],
    limitsNotes: ['Anything beyond these is Additional Work.'],
    completion: [
      "The workspace is active on the Client's domain, every mailbox listed sends and receives successfully through a test message, authentication records pass validation, and administrative access has been transferred.",
    ],
    receives: [
      'Full administrative access to the workspace',
      'All mailbox credentials, for onward distribution by the Client',
      'A record of the authentication records configured',
      'A handover walkthrough covering the admin console',
    ],
    receivesNotes: [],
    thirdPartyCosts:
      'Workspace subscription and per-seat charges · additional storage · any paid add-on · domain renewal',
    exclusionIds: [
      'E30', 'E31', 'E48', 'E49', 'E52', 'E53', 'E57', 'E72', 'E82', 'E83', 'E85', 'E87',
    ],
    clientInputIds: ['I02', 'I06', 'I26', 'I27', 'I28', 'I62'],
    fee: [
      { label: 'Fee', value: '[ ]' },
      { label: 'Payment', value: 'in full in advance, or within a Build advance' },
      { label: 'Timeline', value: '[3] working days from receipt of inputs' },
      { label: 'Correction window', value: '[14] days' },
    ],
  },
  {
    code: '19',
    name: 'Analytics and tracking',
    scheduleKey: 'setup',
    sortOrder: 19,
    archived: false,
    dependencies: [],
    pairings: ['07', '13', '15'],
    overview: [
      'Setup of analytics and conversion tracking so the Client can see what people do on its property — property creation, tag deployment, event configuration and a working report view.',
    ],
    included: [
      "Analytics property creation on the Client's account",
      'Tag manager container setup and deployment',
      'Configuration of up to [6] conversion events',
      'Advertising pixel installation for up to [2] platforms',
      'Ecommerce or form-submission tracking, where applicable',
      'Cross-domain configuration, where [1] additional domain is in scope',
      'Verification that every event fires correctly',
      '[1] report view or dashboard covering the configured events',
      'One handover walkthrough',
    ],
    accountTerms: [
      "All analytics, tag and advertising accounts are created in the Client's name and owned by the Client from creation. Qera Private Limited holds access only for setup and, where a related retainer is attached, for its duration.",
      'Measurement is approximate. Ad blockers, browser tracking restrictions, cookie consent choices, device switching and platform attribution models all cause undercounting and discrepancy between platforms. Figures from two platforms will not match and neither is wrong.',
      "Privacy and consent compliance is the Client's responsibility. Cookie consent, privacy notices, data processing agreements and compliance with applicable data protection law are not included in this Part and require the Client's own legal advice.",
      'Historic data cannot be backfilled into a newly created property. Measurement begins from the date of installation.',
    ],
    limits: [
      { label: 'Analytics properties', value: '[1]' },
      { label: 'Conversion events', value: '[6]' },
      { label: 'Advertising pixels', value: '[2]' },
      { label: 'Additional domains', value: '[1]' },
      { label: 'Dashboards or report views', value: '[1]' },
    ],
    limitsNotes: ['Anything beyond these is Additional Work.'],
    completion: [
      'Every configured event fires correctly under test, tags are live on the property, pixels report receiving data, and the dashboard displays the configured events.',
      "Data accuracy against any other platform's figures is not an acceptance criterion.",
    ],
    receives: [
      'Full ownership of every analytics and tag account',
      'A written record of every event and tag configured',
      'The dashboard or report view',
      'A handover walkthrough covering where to find each figure',
    ],
    receivesNotes: [],
    thirdPartyCosts:
      'Analytics platform subscriptions, where a paid tier is used · consent management tool subscriptions · any paid tag or tracking service',
    exclusionIds: [
      'E22', 'E25', 'E27', 'E30', 'E38', 'E39', 'E45', 'E46', 'E48', 'E49', 'E52',
      'E54', 'E56', 'E64', 'E85', 'E86', 'E88', 'E89',
    ],
    clientInputIds: ['I01', 'I03', 'I07', 'I26', 'I27', 'I28', 'I37'],
    fee: [
      { label: 'Fee', value: '[ ]' },
      { label: 'Payment', value: 'in full in advance, or within a Build advance' },
      { label: 'Timeline', value: '[5] working days from receipt of inputs' },
      { label: 'Correction window', value: '[14] days' },
    ],
  },
  {
    code: '20',
    name: 'Social account setup and verification',
    scheduleKey: 'setup',
    sortOrder: 20,
    archived: false,
    dependencies: ['05'],
    pairings: ['11', '12', '13'],
    overview: [
      'Creation and configuration of social accounts on the platforms the Client needs — handles, profile setup, business account conversion, and the business portfolio structure required to run advertising.',
    ],
    included: [
      'Handle availability check across up to [5] platforms',
      'Account creation on up to [5] platforms',
      'Conversion to business or professional account type',
      'Profile setup — image, banner, bio, links and contact details, from Client-supplied assets',
      "Business portfolio or business manager creation, in the Client's name",
      'Ad account creation and linking, where advertising is in scope',
      "Linking of accounts to each other and to the Client's site",
      "Two-factor and recovery configuration, on the Client's own details",
      'Submission of [1] verification application per platform, where the Client qualifies',
      'Credential handover and one walkthrough',
    ],
    accountTerms: [
      "Every account, business portfolio and ad account is created in the Client's name and owned by the Client from creation. Where advertising is in scope, the ad account sits inside the Client's own business portfolio, and Qera Private Limited operates as an assigned partner rather than as owner. Qera Private Limited does not create Client accounts under its own portfolio.",
      "Two-factor authentication and recovery are configured against the Client's own phone number and recovery email. The Client is responsible for retaining these. Qera Private Limited cannot recover an account for which the Client has lost recovery access.",
      "Handle availability is not guaranteed. A preferred name may already be taken, reserved or restricted. Alternatives are agreed from the Client's priority list.",
      'Verification outcomes are not guaranteed. Approval, badge issuance, reinstatement and eligibility are decided entirely by the platform against criteria it does not publish and may change. A declined application does not reduce the fee, and reapplication is Additional Work.',
    ],
    limits: [
      { label: 'Platforms', value: '[5]' },
      { label: 'Verification applications', value: '[1] per platform' },
      { label: 'Business portfolios', value: '[1]' },
      { label: 'Ad accounts', value: '[1]' },
      { label: 'Profile revision rounds', value: '[1]' },
    ],
    limitsNotes: ['Anything beyond these is Additional Work.'],
    completion: [
      'Every account listed is created, converted to the correct type, configured with the supplied profile assets, secured with two-factor authentication, linked as agreed, and credentials have been delivered to the Client.',
      "Submission of a verification application completes that item. The platform's decision does not.",
    ],
    receives: [
      'Full ownership of every account created',
      'All credentials and recovery configuration details',
      'Business portfolio and ad account under its own ownership',
      'A written record of every account, handle and link created',
      'A handover walkthrough',
    ],
    receivesNotes: [],
    thirdPartyCosts:
      'Any paid verification or subscription tier · advertising spend · profile photography or asset production · business documentation costs required for verification',
    exclusionIds: [
      'E01', 'E02', 'E03', 'E32', 'E34', 'E38', 'E39', 'E40', 'E44', 'E46', 'E48',
      'E52', 'E55', 'E57', 'E58', 'E75', 'E76', 'E77', 'E85', 'E90', 'E91',
    ],
    clientInputIds: ['I05', 'I17', 'I19', 'I21', 'I26', 'I27', 'I28', 'I52', 'I64', 'I65'],
    fee: [
      { label: 'Fee', value: '[ ]' },
      { label: 'Payment', value: 'in full in advance, or within a Build advance' },
      { label: 'Timeline', value: '[5] working days from receipt of inputs' },
      { label: 'Correction window', value: '[14] days' },
    ],
  },
  {
    code: '21',
    name: 'Audit or teardown',
    scheduleKey: 'audit',
    sortOrder: 21,
    archived: false,
    dependencies: [],
    pairings: ['07', '02', '03', '16'],
    overview: [
      'Structured review of an existing property, system or presence, delivered as a written document setting out findings, their commercial significance and prioritised recommendations.',
      'This Part delivers analysis. Implementation of any recommendation constitutes a separate engagement under the Build, Retainer or Setup Schedule.',
    ],
    included: [
      'Review of [1] property or system, being a website, storefront, social presence, automation system or brand presence as specified',
      'Examination of up to [5] page templates, screens or workflows',
      'Review of available analytics covering not less than [3] months, where access is provided',
      'Comparison against [3] competitors or comparable operators',
      'Written findings document setting out each finding, its likely commercial effect and a recommended course of action',
      'Prioritisation of recommendations by expected impact and implementation effort',
      '[1] walkthrough session of up to [45] minutes',
    ],
    accountTerms: [
      'Analysis is conducted upon material and access supplied by the Client together with information publicly observable. Where access or information is not supplied, the findings shall be limited accordingly and such limitation shall be recorded in the findings document.',
      'Findings represent professional opinion formed on the information available as at the date of analysis. They do not constitute a prediction of outcome, a guarantee of improvement, or legal, tax, financial or regulatory advice.',
      'The Client shall determine which recommendations, if any, to implement. Qera Private Limited shall bear no responsibility for the consequences of implementation, whether effected by the Client, by Qera Private Limited under another Schedule, or by any third party.',
      'Where the property examined was produced by a third party, findings are recorded as observations and shall not constitute an allegation of professional deficiency against any person.',
    ],
    limits: [
      { label: 'Properties or systems reviewed', value: '[1]' },
      { label: 'Page templates, screens or workflows examined', value: '[5]' },
      { label: 'Competitors compared', value: '[3]' },
      { label: 'Walkthrough sessions', value: '[1], up to [45] minutes' },
      { label: 'Analytics platforms reviewed', value: '[1]' },
      { label: 'Clarification period following delivery', value: '[14 days]' },
    ],
    limitsNotes: ['Anything beyond these limits constitutes Additional Work.'],
    completion: [
      'The findings document has been delivered in the form specified above and the walkthrough session has been held or has been offered and declined.',
      "The Client's agreement with any finding, and the commercial outcome of acting upon any recommendation, are not criteria of completion.",
    ],
    receives: [
      'The findings document in PDF format',
      'A prioritised list of recommendations, each with an indicative implementation route',
      'A recording of the walkthrough session, where the Client requests one',
      'Answers to reasonable clarifying questions on the content of the document for [14 days] following delivery',
    ],
    receivesNotes: [],
    thirdPartyCosts:
      'Analytics or research tool subscriptions, where a paid tier is required · access costs for any platform under review',
    exclusionIds: [
      'E25', 'E38', 'E39', 'E45', 'E46', 'E52', 'E56', 'E63', 'E64', 'E65', 'E66',
      'E85', 'E86', 'E89',
    ],
    clientInputIds: ['I01', 'I03', 'I07', 'I26', 'I28', 'I31', 'I37', 'I44', 'I45', 'I60'],
    fee: [
      { label: 'Fee', value: '[ ]' },
      { label: 'Payment', value: 'in full in advance' },
      { label: 'Timeline', value: '[7] working days from receipt of inputs' },
      { label: 'Clarification period', value: '[14] days from delivery' },
    ],
  },
  {
    code: '22',
    name: 'Strategy sprint',
    scheduleKey: 'audit',
    sortOrder: 22,
    archived: false,
    dependencies: [],
    pairings: ['11', '13'],
    overview: [
      'A time-boxed engagement addressing a defined strategic question, delivered through working sessions and a written recommendation document.',
      'This Part delivers a recommended course of action. Execution of that course of action constitutes a separate engagement under the Build, Retainer or Setup Schedule.',
    ],
    included: [
      'Definition of [1] strategic question, agreed in writing prior to commencement',
      'Review of material and data supplied by the Client',
      '[2] working sessions of up to [90] minutes each, with up to [3] Client participants',
      'Market and competitor context covering [3] comparable operators',
      'Written recommendation document setting out the recommended course of action, the principal alternatives considered, and the reasons for the recommendation',
      'Outline implementation sequence, with indicative effort and dependencies',
      'Identification of the assumptions upon which the recommendation depends',
    ],
    accountTerms: [
      'The recommendation is formed upon information supplied by the Client and upon publicly available information. Its soundness depends upon the accuracy and completeness of the information supplied, and the Client warrants that information supplied is accurate to the best of its knowledge.',
      'The recommendation represents professional opinion formed as at the date of delivery. It does not constitute a guarantee of commercial outcome, and does not constitute legal, tax, financial, employment or regulatory advice. The Client shall obtain its own professional advice in respect of any such matter.',
      'Qera Private Limited shall have no responsibility for any decision taken by the Client, whether consistent with the recommendation or otherwise, nor for any outcome arising from it.',
      'Where Qera Private Limited is subsequently engaged to implement any part of the recommendation, such engagement shall be governed by the applicable Schedule and shall be separately quoted. This Part shall not be construed as a commitment by either Party to any subsequent engagement.',
    ],
    limits: [
      { label: 'Strategic questions addressed', value: '[1]' },
      { label: 'Working sessions', value: '[2], up to [90] minutes each' },
      { label: 'Client participants per session', value: '[3]' },
      { label: 'Comparable operators reviewed', value: '[3]' },
      { label: 'Revision of the recommendation document', value: '[1], for factual correction only' },
      { label: 'Clarification period following delivery', value: '[14 days]' },
    ],
    limitsNotes: [
      'Anything beyond these limits constitutes Additional Work.',
      'Where the strategic question is materially altered following commencement, the engagement shall be re-scoped and re-quoted.',
    ],
    completion: [
      'The working sessions have been held or have been offered and declined, and the recommendation document has been delivered in the form specified above.',
      "The Client's agreement with the recommendation, and the commercial outcome of adopting it, are not criteria of completion.",
    ],
    receives: [
      'The recommendation document in PDF format',
      'Recordings of the working sessions, where the Client requests them',
      'The outline implementation sequence',
      'Answers to reasonable clarifying questions on the content of the document for [14 days] following delivery',
    ],
    receivesNotes: [],
    thirdPartyCosts:
      'Research or data subscriptions, where a paid tier is required · any third-party report procured at the Client’s request',
    exclusionIds: ['E01', 'E45', 'E46', 'E52', 'E56', 'E61', 'E63', 'E65', 'E71', 'E85'],
    clientInputIds: ['I01', 'I26', 'I28', 'I31', 'I33', 'I34', 'I37', 'I45'],
    fee: [
      { label: 'Fee', value: '[ ]' },
      { label: 'Payment', value: 'in full in advance' },
      { label: 'Timeline', value: '[10] working days from commencement' },
      { label: 'Clarification period', value: '[14] days from delivery' },
    ],
  },
];
